---
language: shell
dist: 20.04

before_install:
  - sudo apt update -y
  - sudo apt install -y hugo

script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  token: $GH_TOKEN
  on:
    branch: main
