baseURL = "https://lamlex.github.io/cs795-lp"
languageCode = "en-us"
title = "Travis et. al: 3rd party CI/CD services"

theme = "reveal-hugo"

footnoteReturnLinkContents = "↩"
enableGitInfo = true

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true